### ISSUE TITLE
RPM Stuck at ~1100

### ISSUE THREAD

**Issue by WhiteIntel** [sandalle/minecraft_bigreactor_control#44]
Hello,
I have the following setup:
2 reactors, actively cooled with 2 turbines with enderium coils.
![2014-12-16_19 23 53](https://cloud.githubusercontent.com/assets/4647303/5459216/656401ac-8559-11e4-964b-37c37cabb5fb.png)
![2014-12-16_19 24 04](https://cloud.githubusercontent.com/assets/4647303/5459212/65626f40-8559-11e4-85cd-8c29e8dc84d0.png)
![2014-12-16_19 24 10](https://cloud.githubusercontent.com/assets/4647303/5459213/65630a2c-8559-11e4-9c36-c6365c6ff54d.png)
![2014-12-16_19 24 13](https://cloud.githubusercontent.com/assets/4647303/5459215/6563a784-8559-11e4-9af8-26a91e1f5b46.png)
![2014-12-16_19 24 23](https://cloud.githubusercontent.com/assets/4647303/5459214/6563ad6a-8559-11e4-96bd-fbf3dae19658.png)
![2014-12-16_19 24 35](https://cloud.githubusercontent.com/assets/4647303/5459217/656a80c2-8559-11e4-928f-1a0c65f562f1.png)
![2014-12-16_19 25 10](https://cloud.githubusercontent.com/assets/4647303/5459219/657e3874-8559-11e4-9a0f-b47a2af29f28.png)
![2014-12-16_19 25 33](https://cloud.githubusercontent.com/assets/4647303/5459218/65776468-8559-11e4-85d2-a632e6084c0d.png)

I attached some screenshots of my setup, I also tried deleting the configs and reset the reactor states, but still the same :\

greetings

**Comment by walliski** [comment]
I suppose that they work without the computer then, if you run both reactor and turbine manually?

**Comment by sandalle** [comment]
@walliski has a good point, can you manually get them (with the script off) to go over 1,100 RPM? Your screenshot shows two turbines and that your two reactors only make a combined 2,564 mB/t of steam. Your one turbine in the screenshot shows that it'll accept up to 2,000 mB/t of steam, but that doesn't mean it is getting 2,000 mB/t of steam (it actually appears empty of steam, so might be starved of steam).

**Comment by sandalle** [comment]
This seems to no longer be an issue when using 0.3.17 thanks to Push #52 , though I didn't see it earlier either.
![2015-03-31_10 43 25](https://cloud.githubusercontent.com/assets/2447608/6925256/1c0a13de-d793-11e4-879c-e99867bc2368.png)

**Comment by sandalle** [comment]
I commited https://github.com/sandalle/minecraft_bigreactor_control/commit/f4d8a85e18d614ebb729a99bca202aac23e7cf5a to help troubleshoot this and will leave it in as it's handy to see. :)
