### ISSUE TITLE
Turbine automatic shutdown

### ISSUE THREAD

**Issue by Droxtor** [sandalle/minecraft_bigreactor_control#45]
I have reactor and three turbines but turbines not turning off when buffer is full

![2015-01-03_02 22 24](https://cloud.githubusercontent.com/assets/6633164/5600937/8de757fc-92ef-11e4-8987-82237d6c7cd8.png)
![2015-01-03_02 22 22](https://cloud.githubusercontent.com/assets/6633164/5600936/8de6cc74-92ef-11e4-8f5e-cabe78ad0793.png)

**Comment by sandalle** [comment]
We don't currently turn off the turbines, see #7 for why and the enhancement request and a method to spin the turbines back up quickly (the clutch which @mechaet proposed).
