### ISSUE TITLE
Please make monitors optional

### ISSUE THREAD

**Issue by Zehir** [sandalle/minecraft_bigreactor_control#46]
Hello, the latest version of ComputerCraft have a bug with the monitors, as soon as teleports near a crash game screen. I tried to increase the variable loop time without success.
Could you make a version without monitor. A monitor may be attached to the configuration, but once made thereto, only the computer would be used.

thank you

**Comment by sandalle** [comment]
I can look into this, though without at least one 3x3 Advanced Monitor, you won't be able to adjust the settings without editing the configuration files.

**Comment by Zehir** [comment]
I moved from the reactors of a few dozen blocks and I have no problems. But it's a good idea to make optional monitors.
