### ISSUE TITLE
Newest version not in pastebin?

### ISSUE THREAD

**Issue by walliski** [sandalle/minecraft_bigreactor_control#47]
The one that is linked to pastebin is older version, which does not work with 1.58 (Tekkit) it seems?

**Comment by sandalle** [comment]
I was pending someone testing #5 , but have updated the pastebin with 0.3.15 now as it worked in my testing. :)

**Comment by walliski** [comment]
Aah, would you look at that. Worked for 1.58 for me. Although it doesnt seem to control the turbine all the time. It says the turbine is online, but doesnt get/set the correct values. The computercraft monitor changes, but not the turbine. Switching the turbine to manual override, and back to automatic fixes this.

Also, are turbines supposed to stop or spin down when they are not needed? Ours just keeps going...

**Comment by sandalle** [comment]
For the Turbines, we keep them running all the time. See Issue #7 for tracking improvement to this. :)

Do you have to flip to manual override every time you change values or just the once, and then the program manages the turbines correctly from then on? Are you seeing Issue #44 or maybe something else?

**Comment by walliski** [comment]
It's something else. It happens when changing something on the turbine, breaking the multiblock. Doesn't help to terminate the program and restart it, and it doesn't help to even break the computer and put it back. But disabling and enabling autocontrol makes it work. 

When turbine starts the monitor says 2000 mb/t, but the turbine stays on 290 (the previous value).
