### ISSUE TITLE
Monitor Scale Inaccurate

### ISSUE THREAD

**Issue by TeamDman** [sandalle/minecraft_bigreactor_control#50]
Program thinks the monitor setup is the wrong size if the text scale was previously enlarged.

**Comment by sandalle** [comment]
Text scale in...Minecraft or you've modified the code to do ComputerCraft text scaling?

**Comment by TeamDman** [comment]
I had ran previous CC programs which modified the scale of text on the
monitor using one of the functions they have.

**Comment by sandalle** [comment]
I do set the text scale every loop (See https://github.com/sandalle/minecraft_bigreactor_control/blob/master/lolmer_bigreactor_monitor_prog.lua#L558) and it has to be done to each monitor, not a general setting. I'll move this to the findMonitors() function before I check getSize().
