### ISSUE TITLE
Reactor Online/Offline input non-responsive when reactor is converted from passive to active cooled

### ISSUE THREAD

**Issue by VinylTheUnicorn** [sandalle/minecraft_bigreactor_control#61]
hello, after running the lua script on my server my reactors refuse to respond to the offline/online input. Everything else works flawlessly. my turbines are responsive to monitor inputs as well as the other options for the reactors. The reactors just wont turn on with the monitor input nor by  manually turning them on unless I fully disconnect the computercraft system from the reactors. I fall in line with the requirements and I followed the set up guide so I figure this must be a bug but if not any and all help is appreciated.

**Comment by sandalle** [comment]
HI @VinylTheUnicorn , which version of the script are you using? What version of Minecraft and ComputerCraft are you using? I'll do some testing tonight, but this was working with Minecraft 1.6.4 and ComputerCraft 1.58 on [NST: Diet](http://www.technicpack.net/modpack/details/never-stop-toasting-diet.254882) last I recall.

**Comment by VinylTheUnicorn** [comment]
hello, i found the issue. it has to do with how the script works. my reactors use to be passively cooled then i made them actively cooled to run turbines. because of this the internal energy storage of the reactors were full and because of how the script is built it would keep the reactors off even though they weren't passively cooled anymore and that energy bar was no longer a factor. maybe there is a better way to execute this function within your script to prevent this from happening? or was i just missing something?  i did however run into a new bug as well as an old one that may or may not have been fixed maybe its just me. 1) this may or may not pertain to your script but when loading the script on the cc computer it states that all the peripherals have been found and connected but after backing out the monitors are blank but the script is still running because my reactors turn on and are being regulated by the script. 2) when the monitors were working they weren't loading in the order they were described to load in. have you ever found a resolution for this?
im running ez-nuke 0.3.16 cc 1.73 and mc 1.7.10. thanks.

**Comment by sandalle** [comment]
Several options to fix this. I could modify getReactorStoredEnergyBufferPercent to check if the reactor is actively cooled and, if so, to return "0" energy stored, but then that might just lead to an actively cooled reactor to be turned on, instead of off, after it's been converted from passively cooled. :)

The better option would be to modify main() to ignore stored energy for actively cooled reactors when determining if the reactor should be set to online or offline.

**Comment by sandalle** [comment]
This will be fixed in the next release, v0.3.18, thanks for the report. :)
