### ISSUE TITLE
Update pastbin program

### ISSUE THREAD

**Issue by Zehir** [sandalle/minecraft_bigreactor_control#66]
Please update your program on pastbin, it's 0.3.17

Thank

**Comment by sandalle** [comment]
My [pastebin](http://pastebin.com/fguScPBQ) is on version [0.3.17](https://github.com/sandalle/minecraft_bigreactor_control/releases/tag/lolmer_bigreactor-0.3.17), which is the latest [release](https://github.com/sandalle/minecraft_bigreactor_control/releases). Please make sure you are using the correct link and not the [test pastebin](http://pastebin.com/GzZwuV8w) which is on the unreleased 0.3.18.
