### ISSUE TITLE
Pastebin.com... Failed

### ISSUE THREAD

**Issue by jeremyshanesmith73** [sandalle/minecraft_bigreactor_control#67]
I tried to do:  pastebin get ZTMzRLez startup
I got:  Connecting to pastebin.com... Failed

So I created a file:  edit startup
I typed a 'd,' then saved it, then Exit

I opened up 'startup' file with Notepad++, deleted the 'd,' then did a COPY/PASTE of the ZTMzRLez code, SAVE, EXIT

I tried to run program:
Np matching files
Connecting to pastebin.com... Failed
No such program

Please help :(

PS:  I am running Minecraft 1.7.10 (SkyFactory2)(ATLauncher)

**Comment by sandalle** [comment]
Your server (or local box) need to allow the ComputerCraft HTTP API, see http://www.computercraft.info/forums2/index.php?/topic/3724-how-do-i-download-pastebin-code-via-http-api/ . This has nothing to do with my script or tooling, but please let me know if you have any further issues. :)
