### ISSUE TITLE
Turbines not being controlled properly

### ISSUE THREAD

**Issue by DFrostedWang** [sandalle/minecraft_bigreactor_control#7]
This doesn't seem to be able to control turbines and reactors together... which is something I was under the impression it would be able to do. Am I wrong in thinking this, or is there just a bug in the code somewhere?

*EDIT* :  So I looked through the code and didn't find any code for shutting of turbines at a certain percentage... I'd like to request this be added in the same manner the reactors are controlled because adding a turbine means losing that functionality, as far as I can tell, and I don't like that. It seems easy enough to implement... I mean, you're already displaying the turbine's buffer as a percent, shouldn't be hard to have a check for the percentage against the max/min percent and manage it that way.

**Comment by sandalle** [comment]
I believe https://github.com/sandalle/minecraft_bigreactor_control/pull/52, slated for https://github.com/sandalle/minecraft_bigreactor_control/milestones/0.3.17, does close to what you are wanting. Once a threshold is met the coils are disengaged, leaving the turbines to free spin at maximum speed without consuming steam (at least according to the Turbine API).

![2015-03-31_11 14 02](https://cloud.githubusercontent.com/assets/2447608/6925837/23687aae-d797-11e4-9a65-bfc56c4884d2.png)
