### ISSUE TITLE
Error: reactorcontrol:724: attempt to concatenate nil and string

### ISSUE THREAD

**Issue by evan1026** [sandalle/minecraft_bigreactor_control#72]
While trying to hit the right arrow on the monitor. This would normally bring you to the turbine page, but when there are no turbines, the selected error occurs

**Comment by thetaphi** [comment]
Confirmed, my fault. Not a one line fix due to the mess I left in UI.select*

**Comment by TheJulianJES** [comment]
Just wondering, if there's a workaround or maybe a different script which has fixed this issue?

**Comment by sandalle** [comment]
Will mark it fixed then, thanks @TheJulianJES . :)
