### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by MTRNord** [sandalle/minecraft_bigreactor_control#76]
Look at title :)

**Comment by sandalle** [comment]
Copy the contents of https://raw.githubusercontent.com/sandalle/minecraft_bigreactor_control/master/lolmer_bigreactor_startup.lua into your ComputerCraft computer in-game. You can type it by hand (excluding the --[[ ... ]]-- comments), copy it to your Save directory (see http://www.computercraft.info/forums2/index.php?/topic/11566-how-do-i-paste-code-into-my-turtle/ ), or just run:
`pastebin get ZTMzRLez startup` in your ComputerCraft Terminal and restart the OS.

The startup script also has these instructions on how to get the initial startup file on your computer, which will download the latest version every reboot. :)

**Comment by MTRNord** [comment]
ah nice thanks :)
